"""empty message

Revision ID: 7e0e55b39d5e
Revises: 
Create Date: 2024-08-21 16:22:03.821884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e0e55b39d5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taskdailystatistics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_tasks', sa.Integer(), nullable=True))

    with op.batch_alter_table('tasksstatistics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_tasks', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasksstatistics', schema=None) as batch_op:
        batch_op.drop_column('total_tasks')

    with op.batch_alter_table('taskdailystatistics', schema=None) as batch_op:
        batch_op.drop_column('total_tasks')

    # ### end Alembic commands ###
